"use client";

import React, { useCallback, useMemo, useState } from "react";
import {
  AlertCircle,
  Check,
  Clock,
  Copy,
  ExternalLink,
  FileText,
  Loader2,
  Sparkles,
  Trash2,
  Youtube,
} from "lucide-react";
import { toast } from "sonner";

import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { cn } from "@/lib/utils";
import type { YoutubeTranscriptItem } from "@/app/dashboard/detector-de-mentiras/constants";

interface YoutubeTranscriptExtractorProps {
  /** Transcripciones ya agregadas (controlado por el formulario) */
  value: YoutubeTranscriptItem[];
  onChange: (transcripts: YoutubeTranscriptItem[]) => void;
  className?: string;
  /** Máximo de transcripciones que se pueden acumular */
  maxTranscripts?: number;
}

interface FailedUrl {
  url: string;
  error: string;
}

/** Caracteres de la transcripción que se muestran como adelanto en el acordeón */
const PREVIEW_LENGTH = 160;

/** Formatea segundos como "mm:ss" o "h:mm:ss" */
function formatDuration(totalSeconds: number): string {
  const seconds = Math.max(0, Math.floor(totalSeconds));
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  const s = seconds % 60;
  const pad = (n: number) => String(n).padStart(2, "0");
  return h > 0 ? `${h}:${pad(m)}:${pad(s)}` : `${m}:${pad(s)}`;
}

/** Separa el input en URLs individuales (una por línea, coma o espacio) */
function splitUrls(input: string): string[] {
  return Array.from(
    new Set(
      input
        .split(/[\s,]+/)
        .map((url) => url.trim())
        .filter(Boolean)
    )
  );
}

/**
 * Permite pegar URLs de YouTube, transcribirlas y gestionarlas como una lista
 * de acordeones: cada uno muestra un adelanto y, al abrirlo, la transcripción
 * completa (editable). Cada transcripción se puede eliminar por separado.
 */
const YoutubeTranscriptExtractor: React.FC<YoutubeTranscriptExtractorProps> = ({
  value,
  onChange,
  className,
  maxTranscripts = 10,
}) => {
  const [urlInput, setUrlInput] = useState("");
  const [isTranscribing, setIsTranscribing] = useState(false);
  const [failedUrls, setFailedUrls] = useState<FailedUrl[]>([]);
  const [copiedId, setCopiedId] = useState<string | null>(null);

  const transcripts = useMemo(() => value ?? [], [value]);

  const totalCharacters = useMemo(
    () => transcripts.reduce((total, item) => total + (item.text?.length ?? 0), 0),
    [transcripts]
  );

  const transcribe = useCallback(async () => {
    const urls = splitUrls(urlInput);

    if (urls.length === 0) {
      toast.error("Pega al menos una URL de YouTube");
      return;
    }

    // Evitar transcribir dos veces el mismo video
    const alreadyAdded = new Set(transcripts.map((item) => item.videoId));
    const remainingSlots = maxTranscripts - transcripts.length;

    if (remainingSlots <= 0) {
      toast.error(`Ya alcanzaste el máximo de ${maxTranscripts} transcripciones`);
      return;
    }

    setIsTranscribing(true);
    setFailedUrls([]);

    try {
      const response = await fetch("/api/youtube-transcript", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ urls: urls.slice(0, remainingSlots) }),
      });

      const data = await response.json();

      if (!response.ok || !data.success) {
        throw new Error(data.error || "No se pudieron obtener las transcripciones");
      }

      const added: YoutubeTranscriptItem[] = [];
      const failed: FailedUrl[] = [];

      for (const result of data.results as any[]) {
        if (result.error) {
          failed.push({ url: result.url, error: result.error });
          continue;
        }

        if (alreadyAdded.has(result.videoId)) {
          failed.push({
            url: result.url,
            error: "Este video ya fue transcrito",
          });
          continue;
        }

        alreadyAdded.add(result.videoId);
        added.push({
          id: `${result.videoId}-${Date.now()}-${added.length}`,
          videoId: result.videoId,
          url: result.url,
          title: result.title ?? "",
          channel: result.channel ?? "",
          durationSeconds: result.durationSeconds ?? 0,
          thumbnail: result.thumbnail,
          language: result.language,
          isAutoGenerated: Boolean(result.isAutoGenerated),
          text: result.text ?? "",
        });
      }

      if (added.length > 0) {
        onChange([...transcripts, ...added]);
        setUrlInput("");
        toast.success(
          added.length === 1
            ? "Transcripción agregada"
            : `${added.length} transcripciones agregadas`
        );
      }

      setFailedUrls(failed);
      if (failed.length > 0 && added.length === 0) {
        toast.error("No se pudo transcribir ningún video");
      }
    } catch (error) {
      const message =
        error instanceof Error ? error.message : "Error al transcribir los videos";
      toast.error(message);
      setFailedUrls(urls.map((url) => ({ url, error: message })));
    } finally {
      setIsTranscribing(false);
    }
  }, [urlInput, transcripts, onChange, maxTranscripts]);

  const removeTranscript = useCallback(
    (id: string) => {
      onChange(transcripts.filter((item) => item.id !== id));
      toast.success("Transcripción eliminada");
    },
    [transcripts, onChange]
  );

  const updateTranscriptText = useCallback(
    (id: string, text: string) => {
      onChange(
        transcripts.map((item) => (item.id === id ? { ...item, text } : item))
      );
    },
    [transcripts, onChange]
  );

  const copyTranscript = useCallback(async (item: YoutubeTranscriptItem) => {
    try {
      await navigator.clipboard.writeText(item.text);
      setCopiedId(item.id);
      setTimeout(() => setCopiedId(null), 2000);
    } catch {
      toast.error("No se pudo copiar la transcripción");
    }
  }, []);

  return (
    <div className={cn("space-y-3", className)}>
      {/* Entrada de URLs + botón de transcripción */}
      <div className="flex items-start gap-2">
        <Input
          value={urlInput}
          onChange={(event) => setUrlInput(event.target.value)}
          onKeyDown={(event) => {
            if (event.key === "Enter") {
              event.preventDefault();
              if (!isTranscribing) transcribe();
            }
          }}
          placeholder="Pega una o varias URLs de YouTube (una por línea o separadas por coma)"
          disabled={isTranscribing}
          className="flex-1"
        />
        <Button
          type="button"
          onClick={transcribe}
          disabled={isTranscribing || urlInput.trim().length === 0}
          className="shrink-0 bg-red-600 text-white hover:bg-red-700"
        >
          {isTranscribing ? (
            <>
              <Loader2 className="w-4 h-4 mr-2 animate-spin" />
              Transcribiendo...
            </>
          ) : (
            <>
              <Youtube className="w-4 h-4 mr-2" />
              Transcribir videos
            </>
          )}
        </Button>
      </div>

      {/* URLs que no se pudieron transcribir */}
      {failedUrls.length > 0 && (
        <div className="space-y-2">
          {failedUrls.map((failed) => (
            <div
              key={failed.url}
              className="flex items-start gap-2 rounded-lg border border-red-200 bg-red-50 px-3 py-2"
            >
              <AlertCircle className="mt-0.5 h-4 w-4 shrink-0 text-red-500" />
              <div className="min-w-0 flex-1">
                <p className="truncate font-mono text-xs text-red-700">
                  {failed.url}
                </p>
                <p className="text-xs text-red-600">{failed.error}</p>
              </div>
              <Button
                type="button"
                variant="ghost"
                size="sm"
                onClick={() =>
                  setFailedUrls((current) =>
                    current.filter((item) => item.url !== failed.url)
                  )
                }
                className="h-6 w-6 shrink-0 p-0 text-red-500 hover:text-red-700"
                title="Descartar"
              >
                <Trash2 className="h-3 w-3" />
              </Button>
            </div>
          ))}
        </div>
      )}

      {/* Lista de transcripciones */}
      {transcripts.length > 0 && (
        <>
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <Badge
                variant="secondary"
                className="border-red-200 bg-red-50 text-red-700"
              >
                <Youtube className="mr-1.5 h-3 w-3" />
                {transcripts.length}{" "}
                {transcripts.length === 1 ? "transcripción" : "transcripciones"}
              </Badge>
              <Badge
                variant="outline"
                className="border-gray-300 bg-gray-50 text-gray-700"
              >
                <FileText className="mr-1.5 h-3 w-3" />
                {totalCharacters.toLocaleString()} caracteres
              </Badge>
            </div>
            <Button
              type="button"
              variant="ghost"
              size="sm"
              onClick={() => {
                onChange([]);
                toast.success("Transcripciones eliminadas");
              }}
              className="h-7 text-xs text-gray-500 hover:text-red-600"
            >
              Eliminar todas
            </Button>
          </div>

          <Accordion type="multiple" className="space-y-2">
            {transcripts.map((item) => {
              const text = item.text ?? "";
              const preview = text.slice(0, PREVIEW_LENGTH).trim();

              return (
                <AccordionItem
                  key={item.id}
                  value={item.id}
                  className="relative overflow-hidden rounded-xl border border-gray-200/60 bg-white shadow-sm transition-all hover:border-gray-300/80 hover:shadow-md"
                >
                  {/* Eliminar: fuera del trigger para no anidar botones */}
                  <div className="absolute right-3 top-3 z-10">
                    <Button
                      type="button"
                      variant="ghost"
                      size="sm"
                      onClick={() => removeTranscript(item.id)}
                      className="h-8 w-8 border border-gray-200/50 bg-white/80 p-0 text-red-500 shadow-sm backdrop-blur-sm hover:border-red-200 hover:bg-red-50 hover:text-red-700"
                      title="Eliminar transcripción"
                    >
                      <Trash2 className="h-3.5 w-3.5" />
                    </Button>
                  </div>

                  <AccordionTrigger className="px-4 py-3 pr-14 hover:no-underline">
                    <div className="flex w-full gap-3 text-left">
                      {/* Miniatura */}
                      <div className="shrink-0">
                        {item.thumbnail ? (
                          <img
                            src={item.thumbnail}
                            alt=""
                            className="h-16 w-28 rounded-lg border border-gray-200/60 object-cover"
                            onError={(event) => {
                              event.currentTarget.style.display = "none";
                            }}
                          />
                        ) : (
                          <div className="flex h-16 w-28 items-center justify-center rounded-lg border border-gray-200/60 bg-gray-100">
                            <Youtube className="h-7 w-7 text-gray-400" />
                          </div>
                        )}
                      </div>

                      {/* Datos parciales */}
                      <div className="min-w-0 flex-1">
                        <h4 className="line-clamp-1 text-sm font-semibold text-gray-900">
                          {item.title || "Video de YouTube"}
                        </h4>
                        <p className="mb-1.5 line-clamp-1 text-xs text-gray-500">
                          {item.channel}
                        </p>
                        <p className="mb-2 line-clamp-2 text-xs leading-relaxed text-gray-600">
                          {preview
                            ? `${preview}${
                                text.length > PREVIEW_LENGTH ? "…" : ""
                              }`
                            : "Sin contenido en la transcripción"}
                        </p>

                        <div className="flex flex-wrap items-center gap-1.5">
                          {item.durationSeconds > 0 && (
                            <Badge
                              variant="outline"
                              className="border-gray-300 bg-gray-50 text-gray-700"
                            >
                              <Clock className="mr-1 h-3 w-3" />
                              {formatDuration(item.durationSeconds)}
                            </Badge>
                          )}
                          <Badge
                            variant="outline"
                            className="border-gray-300 bg-gray-50 text-gray-700"
                          >
                            <FileText className="mr-1 h-3 w-3" />
                            {text.length.toLocaleString()} caracteres
                          </Badge>
                          {item.language && (
                            <Badge
                              variant="secondary"
                              className="border-blue-200 bg-blue-50 text-blue-700"
                            >
                              {item.language}
                            </Badge>
                          )}
                          {item.isAutoGenerated && (
                            <Badge
                              variant="secondary"
                              className="border-amber-200 bg-amber-50 text-amber-700"
                              title="Subtítulos generados automáticamente por YouTube"
                            >
                              <Sparkles className="mr-1 h-3 w-3" />
                              Automática
                            </Badge>
                          )}
                        </div>
                      </div>
                    </div>
                  </AccordionTrigger>

                  {/* Transcripción completa */}
                  <AccordionContent className="px-4 pb-4">
                    <div className="space-y-2">
                      <div className="flex items-center justify-between">
                        <span className="text-xs font-medium text-gray-500">
                          Transcripción completa (editable)
                        </span>
                        <div className="flex items-center gap-1">
                          <Button
                            type="button"
                            variant="ghost"
                            size="sm"
                            onClick={() => copyTranscript(item)}
                            className="h-7 w-7 border border-gray-200/50 p-0 hover:bg-gray-100"
                            title="Copiar transcripción"
                          >
                            {copiedId === item.id ? (
                              <Check className="h-3 w-3 text-emerald-600" />
                            ) : (
                              <Copy className="h-3 w-3" />
                            )}
                          </Button>
                          <Button
                            type="button"
                            variant="ghost"
                            size="sm"
                            onClick={() => window.open(item.url, "_blank")}
                            className="h-7 w-7 border border-gray-200/50 p-0 hover:bg-gray-100"
                            title="Abrir video en YouTube"
                          >
                            <ExternalLink className="h-3 w-3" />
                          </Button>
                        </div>
                      </div>

                      <Textarea
                        value={text}
                        onChange={(event) =>
                          updateTranscriptText(item.id, event.target.value)
                        }
                        placeholder="La transcripción aparecerá aquí. También puedes pegarla manualmente."
                        className="max-h-[300px] min-h-[160px] resize-y overflow-y-auto text-xs leading-relaxed"
                      />
                    </div>
                  </AccordionContent>
                </AccordionItem>
              );
            })}
          </Accordion>
        </>
      )}
    </div>
  );
};

export default YoutubeTranscriptExtractor;
export type { YoutubeTranscriptExtractorProps };
