/**
 * Extracción de transcripciones de YouTube.
 *
 * YouTube no expone una API pública para descargar los subtítulos de un video
 * ajeno (`captions.download` de la Data API exige OAuth del dueño del canal),
 * por lo que la extracción se hace con una cadena de proveedores:
 *
 *  1. `timedtext`  - Scraping de la página del video para obtener las pistas de
 *                    subtítulos y descargarlas. Es gratis, pero YouTube lo
 *                    bloquea desde IPs de datacenter (responde 200 con cuerpo
 *                    vacío), así que puede fallar en producción.
 *  2. `rapidapi`   - Proveedor externo opcional. Se activa configurando
 *                    RAPIDAPI_KEY + YOUTUBE_TRANSCRIPT_RAPIDAPI_HOST.
 *
 * Los metadatos (título, canal, duración, miniatura) se obtienen con la Data API
 * usando YOUTUBE_API_KEY, con el scraping como respaldo.
 */

const WATCH_USER_AGENT =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36";

/** Idiomas preferidos, en orden, al elegir la pista de subtítulos */
const PREFERRED_LANGUAGES = ["es", "es-419", "es-ES", "en", "en-US"];

const FETCH_TIMEOUT_MS = 20000;

export interface TranscriptSegment {
  /** Inicio del segmento en segundos */
  start: number;
  /** Duración del segmento en segundos */
  duration: number;
  text: string;
}

export interface YoutubeTranscript {
  videoId: string;
  url: string;
  title: string;
  channel: string;
  /** Duración del video en segundos (0 si no se pudo determinar) */
  durationSeconds: number;
  thumbnail?: string;
  /** Código de idioma de la pista utilizada (ej. "es", "en") */
  language?: string;
  /** true si la pista es generada automáticamente por YouTube (ASR) */
  isAutoGenerated: boolean;
  /** Transcripción completa en texto plano */
  text: string;
  segments: TranscriptSegment[];
  charCount: number;
  /** Proveedor que resolvió la transcripción */
  source: "timedtext" | "rapidapi";
}

export interface YoutubeTranscriptError {
  videoId: string | null;
  url: string;
  error: string;
}

export type YoutubeTranscriptResult = YoutubeTranscript | YoutubeTranscriptError;

export function isTranscriptError(
  result: YoutubeTranscriptResult
): result is YoutubeTranscriptError {
  return "error" in result;
}

/**
 * Extrae el ID de un video a partir de cualquier formato de URL de YouTube
 * (watch, youtu.be, shorts, embed, live) o de un ID suelto.
 * @returns El ID de 11 caracteres o null si la URL no es de YouTube
 */
export function extractYouTubeVideoId(input: string): string | null {
  const value = input.trim();
  if (!value) return null;

  // Un ID suelto de 11 caracteres
  if (/^[\w-]{11}$/.test(value)) return value;

  let url: URL;
  try {
    url = new URL(value.startsWith("http") ? value : `https://${value}`);
  } catch {
    return null;
  }

  const host = url.hostname.replace(/^www\./, "").toLowerCase();
  const isYoutubeHost =
    host === "youtube.com" ||
    host === "m.youtube.com" ||
    host === "music.youtube.com" ||
    host === "youtube-nocookie.com" ||
    host === "youtu.be";

  if (!isYoutubeHost) return null;

  // https://youtu.be/<id>
  if (host === "youtu.be") {
    const id = url.pathname.split("/").filter(Boolean)[0];
    return id && /^[\w-]{11}$/.test(id) ? id : null;
  }

  // https://youtube.com/watch?v=<id>
  const vParam = url.searchParams.get("v");
  if (vParam && /^[\w-]{11}$/.test(vParam)) return vParam;

  // https://youtube.com/{shorts,embed,live,v}/<id>
  const parts = url.pathname.split("/").filter(Boolean);
  if (parts.length >= 2 && ["shorts", "embed", "live", "v"].includes(parts[0])) {
    return /^[\w-]{11}$/.test(parts[1]) ? parts[1] : null;
  }

  return null;
}

/** Indica si una cadena corresponde a una URL de video de YouTube */
export function isYouTubeUrl(input: string): boolean {
  return extractYouTubeVideoId(input) !== null;
}

/** fetch con timeout, para que un proveedor lento no cuelgue la request */
async function fetchWithTimeout(
  url: string,
  init: RequestInit = {},
  timeoutMs = FETCH_TIMEOUT_MS
): Promise<Response> {
  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), timeoutMs);
  try {
    return await fetch(url, {
      ...init,
      signal: controller.signal,
      cache: "no-store",
    });
  } finally {
    clearTimeout(timeoutId);
  }
}

/** Convierte una duración ISO 8601 (ej. "PT1H2M19S") a segundos */
function parseIsoDuration(duration: string): number {
  const match = duration.match(/PT(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?/);
  if (!match) return 0;
  const [, h, m, s] = match;
  return Number(h || 0) * 3600 + Number(m || 0) * 60 + Number(s || 0);
}

/** Formatea segundos como "mm:ss" o "h:mm:ss" */
export function formatTimestamp(totalSeconds: number): string {
  const seconds = Math.max(0, Math.floor(totalSeconds));
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  const s = seconds % 60;
  const pad = (n: number) => String(n).padStart(2, "0");
  return h > 0 ? `${h}:${pad(m)}:${pad(s)}` : `${m}:${pad(s)}`;
}

interface CaptionTrack {
  baseUrl: string;
  languageCode: string;
  /** "asr" cuando la pista es generada automáticamente */
  kind?: string;
  name?: string;
}

interface WatchPageData {
  title?: string;
  channel?: string;
  durationSeconds?: number;
  thumbnail?: string;
  captionTracks: CaptionTrack[];
  playabilityStatus?: string;
  playabilityReason?: string;
}

/**
 * Descarga la página del video y extrae `ytInitialPlayerResponse`, que contiene
 * los metadatos y la lista de pistas de subtítulos disponibles.
 */
async function fetchWatchPageData(videoId: string): Promise<WatchPageData> {
  const response = await fetchWithTimeout(
    `https://www.youtube.com/watch?v=${videoId}&hl=es`,
    {
      headers: {
        "User-Agent": WATCH_USER_AGENT,
        "Accept-Language": "es-ES,es;q=0.9,en;q=0.8",
        // Evita la pantalla de consentimiento de cookies en la UE
        Cookie: "CONSENT=YES+cb.20210328-17-p0.en+FX+100",
      },
    }
  );

  if (!response.ok) {
    throw new Error(`YouTube respondió ${response.status} al abrir el video`);
  }

  const html = await response.text();
  const marker = html.indexOf("ytInitialPlayerResponse");
  if (marker === -1) {
    return { captionTracks: [] };
  }

  const start = html.indexOf("{", marker);
  if (start === -1) return { captionTracks: [] };

  const player = extractJsonObject(html, start);
  if (!player) return { captionTracks: [] };

  const details = player.videoDetails ?? {};
  const thumbnails = details.thumbnail?.thumbnails ?? [];
  const rawTracks =
    player.captions?.playerCaptionsTracklistRenderer?.captionTracks ?? [];

  return {
    title: details.title,
    channel: details.author,
    durationSeconds: details.lengthSeconds
      ? Number(details.lengthSeconds)
      : undefined,
    thumbnail: thumbnails[thumbnails.length - 1]?.url,
    playabilityStatus: player.playabilityStatus?.status,
    playabilityReason:
      player.playabilityStatus?.reason ??
      player.playabilityStatus?.messages?.[0],
    captionTracks: rawTracks
      .filter((track: any) => typeof track?.baseUrl === "string")
      .map((track: any) => ({
        baseUrl: track.baseUrl,
        languageCode: track.languageCode ?? "",
        kind: track.kind,
        name: track.name?.simpleText ?? track.name?.runs?.[0]?.text,
      })),
  };
}

/**
 * Lee un objeto JSON embebido en HTML a partir de la posición de su `{`,
 * respetando llaves dentro de cadenas y caracteres escapados.
 */
function extractJsonObject(html: string, start: number): any | null {
  let depth = 0;
  let inString = false;
  let escaped = false;

  for (let i = start; i < html.length; i++) {
    const char = html[i];

    if (inString) {
      if (escaped) escaped = false;
      else if (char === "\\") escaped = true;
      else if (char === '"') inString = false;
      continue;
    }

    if (char === '"') inString = true;
    else if (char === "{") depth++;
    else if (char === "}") {
      depth--;
      if (depth === 0) {
        try {
          return JSON.parse(html.slice(start, i + 1));
        } catch {
          return null;
        }
      }
    }
  }

  return null;
}

/** Ordena las pistas dejando primero los idiomas preferidos y los no automáticos */
function sortCaptionTracks(tracks: CaptionTrack[]): CaptionTrack[] {
  const rank = (track: CaptionTrack) => {
    const index = PREFERRED_LANGUAGES.findIndex(
      (lang) => lang.toLowerCase() === track.languageCode.toLowerCase()
    );
    const languageRank = index === -1 ? PREFERRED_LANGUAGES.length : index;
    // Las pistas manuales tienen mejor calidad que las autogeneradas (asr)
    return languageRank * 2 + (track.kind === "asr" ? 1 : 0);
  };

  return [...tracks].sort((a, b) => rank(a) - rank(b));
}

function decodeXmlEntities(text: string): string {
  return text
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&#(\d+);/g, (_, code) => String.fromCharCode(Number(code)));
}

/** Parsea el formato `json3` de timedtext */
function parseJson3(body: string): TranscriptSegment[] {
  const data = JSON.parse(body);
  const events: any[] = data?.events ?? [];

  return events
    .filter((event) => Array.isArray(event.segs))
    .map((event) => ({
      start: (event.tStartMs ?? 0) / 1000,
      duration: (event.dDurationMs ?? 0) / 1000,
      text: event.segs
        .map((seg: any) => seg.utf8 ?? "")
        .join("")
        .replace(/\s+/g, " ")
        .trim(),
    }))
    .filter((segment) => segment.text.length > 0);
}

/** Parsea el formato XML clásico de timedtext */
function parseTimedTextXml(body: string): TranscriptSegment[] {
  const segments: TranscriptSegment[] = [];
  const regex = /<text([^>]*)>([\s\S]*?)<\/text>/g;
  let match: RegExpExecArray | null;

  while ((match = regex.exec(body)) !== null) {
    const attrs = match[1];
    const start = Number(attrs.match(/start="([\d.]+)"/)?.[1] ?? 0);
    const duration = Number(attrs.match(/dur="([\d.]+)"/)?.[1] ?? 0);
    const text = decodeXmlEntities(match[2])
      .replace(/<[^>]+>/g, "")
      .replace(/\s+/g, " ")
      .trim();

    if (text) segments.push({ start, duration, text });
  }

  return segments;
}

/** Descarga una pista de subtítulos, probando json3 y luego XML */
async function downloadCaptionTrack(
  track: CaptionTrack
): Promise<TranscriptSegment[]> {
  const formats = [
    { suffix: "&fmt=json3", parse: parseJson3 },
    { suffix: "", parse: parseTimedTextXml },
  ];

  for (const format of formats) {
    try {
      const response = await fetchWithTimeout(`${track.baseUrl}${format.suffix}`, {
        headers: {
          "User-Agent": WATCH_USER_AGENT,
          "Accept-Language": "es-ES,es;q=0.9,en;q=0.8",
          Referer: "https://www.youtube.com/",
        },
      });

      if (!response.ok) continue;

      const body = await response.text();
      // YouTube responde 200 con cuerpo vacío cuando bloquea la petición
      if (!body.trim()) continue;

      const segments = format.parse(body);
      if (segments.length > 0) return segments;
    } catch {
      // Se intenta con el siguiente formato
    }
  }

  return [];
}

interface ProviderResult {
  segments: TranscriptSegment[];
  language?: string;
  isAutoGenerated: boolean;
}

/** Proveedor 1: scraping de la página + descarga de timedtext */
async function fetchViaTimedText(
  watchData: WatchPageData
): Promise<ProviderResult | null> {
  const tracks = sortCaptionTracks(watchData.captionTracks);

  for (const track of tracks) {
    const segments = await downloadCaptionTrack(track);
    if (segments.length > 0) {
      return {
        segments,
        language: track.languageCode,
        isAutoGenerated: track.kind === "asr",
      };
    }
  }

  return null;
}

/**
 * Proveedor 2 (opcional): API externa de RapidAPI.
 * Se activa con RAPIDAPI_KEY + YOUTUBE_TRANSCRIPT_RAPIDAPI_HOST.
 */
async function fetchViaRapidApi(
  videoId: string
): Promise<ProviderResult | null> {
  const apiKey = process.env.RAPIDAPI_KEY;
  const host = process.env.YOUTUBE_TRANSCRIPT_RAPIDAPI_HOST;
  if (!apiKey || !host) return null;

  const path =
    process.env.YOUTUBE_TRANSCRIPT_RAPIDAPI_PATH ??
    "/transcript?video_id={videoId}&lang=es";
  const url = `https://${host}${path.replace("{videoId}", videoId)}`;

  const response = await fetchWithTimeout(url, {
    headers: {
      "x-rapidapi-key": apiKey,
      "x-rapidapi-host": host,
    },
  });

  if (!response.ok) {
    const detail = await response.text().catch(() => "");
    throw new Error(
      `El proveedor de transcripciones respondió ${response.status}${
        detail ? `: ${detail.slice(0, 200)}` : ""
      }`
    );
  }

  const data = await response.json();
  const segments = normalizeRapidApiSegments(data);
  if (segments.length === 0) return null;

  return {
    segments,
    language: findRapidApiLanguage(data),
    isAutoGenerated: false,
  };
}

/**
 * Normaliza la respuesta de RapidAPI a segmentos. Cada API devuelve una forma
 * distinta, así que se buscan las claves más comunes de forma tolerante.
 */
function normalizeRapidApiSegments(data: any): TranscriptSegment[] {
  const candidates = [
    data?.transcription,
    data?.transcript,
    data?.content,
    data?.data,
    data?.[0]?.transcription,
    Array.isArray(data) ? data : undefined,
  ];

  const list = candidates.find((value) => Array.isArray(value) && value.length > 0);
  if (!list) return [];

  return (list as any[])
    .map((item) => {
      if (typeof item === "string") {
        return { start: 0, duration: 0, text: item.trim() };
      }
      const text = String(item?.text ?? item?.subtitle ?? item?.snippet ?? "").trim();
      return {
        start: Number(item?.start ?? item?.offset ?? item?.startTime ?? 0),
        duration: Number(item?.duration ?? item?.dur ?? 0),
        text,
      };
    })
    .filter((segment) => segment.text.length > 0);
}

function findRapidApiLanguage(data: any): string | undefined {
  const value = data?.lang ?? data?.language ?? data?.[0]?.lang;
  return typeof value === "string" ? value : undefined;
}

/** Metadatos vía Data API v3 (más fiable que el scraping cuando hay API key) */
async function fetchMetadataFromDataApi(videoId: string) {
  const apiKey = process.env.YOUTUBE_API_KEY;
  if (!apiKey) return null;

  try {
    const response = await fetchWithTimeout(
      `https://www.googleapis.com/youtube/v3/videos?part=snippet,contentDetails&id=${videoId}&key=${apiKey}`
    );
    if (!response.ok) return null;

    const data = await response.json();
    const item = data?.items?.[0];
    if (!item) return null;

    const thumbnails = item.snippet?.thumbnails ?? {};
    return {
      title: item.snippet?.title as string | undefined,
      channel: item.snippet?.channelTitle as string | undefined,
      durationSeconds: parseIsoDuration(item.contentDetails?.duration ?? ""),
      thumbnail: (thumbnails.maxres ?? thumbnails.high ?? thumbnails.medium ?? thumbnails.default)
        ?.url as string | undefined,
    };
  } catch {
    return null;
  }
}

/** Une los segmentos en texto plano legible */
function buildPlainText(segments: TranscriptSegment[]): string {
  return segments
    .map((segment) => segment.text)
    .join(" ")
    .replace(/\s+/g, " ")
    .trim();
}

/**
 * Obtiene la transcripción de un video de YouTube.
 * @param input URL del video (o su ID)
 * @returns La transcripción con sus metadatos, o un objeto con `error`
 */
export async function getYouTubeTranscript(
  input: string
): Promise<YoutubeTranscriptResult> {
  const videoId = extractYouTubeVideoId(input);
  const url = videoId ? `https://www.youtube.com/watch?v=${videoId}` : input;

  if (!videoId) {
    return { videoId: null, url: input, error: "La URL no es de un video de YouTube" };
  }

  try {
    const [metadata, watchData] = await Promise.all([
      fetchMetadataFromDataApi(videoId),
      fetchWatchPageData(videoId).catch(() => ({ captionTracks: [] } as WatchPageData)),
    ]);

    if (!metadata && !watchData.title) {
      return {
        videoId,
        url,
        error:
          watchData.playabilityReason ??
          "No se pudo acceder al video (puede ser privado, eliminado o restringido)",
      };
    }

    let provider: ProviderResult | null = null;
    let providerSource: YoutubeTranscript["source"] = "timedtext";
    let providerError: string | null = null;

    provider = await fetchViaTimedText(watchData);

    if (!provider) {
      try {
        const external = await fetchViaRapidApi(videoId);
        if (external) {
          provider = external;
          providerSource = "rapidapi";
        }
      } catch (error) {
        providerError = error instanceof Error ? error.message : String(error);
      }
    }

    if (!provider) {
      return {
        videoId,
        url,
        error:
          providerError ??
          (watchData.captionTracks.length === 0
            ? "El video no tiene subtítulos disponibles"
            : "YouTube bloqueó la descarga de los subtítulos. Configura YOUTUBE_TRANSCRIPT_RAPIDAPI_HOST o pega la transcripción manualmente."),
      };
    }

    const text = buildPlainText(provider.segments);

    return {
      videoId,
      url,
      title: metadata?.title ?? watchData.title ?? "Video de YouTube",
      channel: metadata?.channel ?? watchData.channel ?? "Canal desconocido",
      durationSeconds: metadata?.durationSeconds || watchData.durationSeconds || 0,
      thumbnail:
        metadata?.thumbnail ??
        watchData.thumbnail ??
        `https://i.ytimg.com/vi/${videoId}/hqdefault.jpg`,
      language: provider.language,
      isAutoGenerated: provider.isAutoGenerated,
      text,
      segments: provider.segments,
      charCount: text.length,
      source: providerSource,
    };
  } catch (error) {
    return {
      videoId,
      url,
      error: error instanceof Error ? error.message : "Error desconocido",
    };
  }
}
