import { createAnthropic } from "@ai-sdk/anthropic";
import { createGoogleGenerativeAI } from "@ai-sdk/google";
import { createOpenAI } from "@ai-sdk/openai";
import { generateText, type ModelMessage } from 'ai';
import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";

import { DebugLogger } from "@/lib/logger";
import { getSupabaseRouteHandler } from "@/lib/supabase/server";
import type { FormSchema } from "@/app/dashboard/detector-de-mentiras/constants";
import {
  formSchema,
  getRatingPromptValue,
} from "@/app/dashboard/detector-de-mentiras/constants";

// Types
interface AuthResult {
  user: any;
  organizationId: string;
  userData: any;
}

interface ApiKeyResult {
  key: string;
  provider: string;
}

interface ToolConfig {
  prompts: any[];
  temperature: number;
  top_p: number;
  schema?: any;
  /** OpenAI `reasoningEffort` / Anthropic `effort` */
  reasoning_effort?: string;
  /** OpenAI `textVerbosity` */
  verbosity?: string;
}

const DEFAULT_REASONING_EFFORT = "medium";
const DEFAULT_VERBOSITY = "medium";

/**
 * Anthropic sólo admite low | medium | high; "xhigh" es exclusivo de OpenAI,
 * así que se recorta al nivel más alto que acepta.
 */
function anthropicEffort(effort: string): "low" | "medium" | "high" {
  return effort === "xhigh" ? "high" : (effort as "low" | "medium" | "high");
}

interface ModelConfig {
  provider: string;
  model: string;
}

// Utility Functions
const searchAndReplaceURLText = (text: string, metadata: any) => {
  const urlRegex = /(https?:\/\/[^\s]+)/g;
  return text.replace(urlRegex, (url) => {
    const meta = metadata?.[url];
    if (meta && meta.complete_text) {
      return `${url} [contenido: ${meta.complete_text}]`;
    }
    return url;
  });
};

/** Formatea segundos como "mm:ss" o "h:mm:ss" */
const formatDuration = (totalSeconds: number): string => {
  const seconds = Math.max(0, Math.floor(totalSeconds));
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  const s = seconds % 60;
  const pad = (n: number) => String(n).padStart(2, "0");
  return h > 0 ? `${h}:${pad(m)}:${pad(s)}` : `${m}:${pad(s)}`;
};

/**
 * Convierte las transcripciones de YouTube en un bloque de texto delimitado
 * para que el modelo pueda citar cada video por separado.
 */
const formatTranscripts = (
  transcripts: FormSchema["additional_context"]["transcripts"]
): string => {
  const withContent = (transcripts ?? []).filter(
    (transcript) => transcript.text?.trim()
  );

  if (withContent.length === 0) return "";

  const blocks = withContent.map((transcript, index) => {
    const metadata = [
      `Título: ${transcript.title || "Sin título"}`,
      `Canal: ${transcript.channel || "Desconocido"}`,
      transcript.durationSeconds
        ? `Duración: ${formatDuration(transcript.durationSeconds)}`
        : null,
      `URL: ${transcript.url}`,
      transcript.isAutoGenerated
        ? "Origen: subtítulos generados automáticamente por YouTube (pueden contener errores de transcripción)"
        : "Origen: subtítulos publicados por el canal",
    ]
      .filter(Boolean)
      .join("\n");

    return `--- VIDEO ${index + 1} ---
${metadata}

Transcripción:
${transcript.text.trim()}`;
  });

  return `

TRANSCRIPCIONES DE VIDEO (${withContent.length}):
Las siguientes son transcripciones textuales de videos aportados como insumo. Úsalas como evidencia citando el video y, cuando sea pertinente, el fragmento correspondiente.

${blocks.join("\n\n")}`;
};

// Authentication function
async function authenticateUser(debugLogger: DebugLogger): Promise<AuthResult> {
  await debugLogger.logAuth("Authenticating user", "authenticating");
  const supabase = await getSupabaseRouteHandler();

  const {
    data: { user },
    error: userAuthError,
  } = await supabase.auth.getUser();

  if (userAuthError || !user) {
    await debugLogger.logAuth("Authentication failed", "failed", undefined, {
      message: "No hay usuario autenticado",
      code: "AUTH_FAILED",
      context: { userAuthError },
    });
    await debugLogger.finalize("failed", {
      error: { message: "No hay usuario autenticado", code: "AUTH_FAILED" },
    });
    throw new Error("No hay usuario autenticado");
  }

  const { data: userData, error: userError } = await supabase
    .from("profiles")
    .select("organizationId, role")
    .eq("id", user.id)
    .single();

  if (userError || !userData?.organizationId) {
    await debugLogger.logAuth(
      "Organization ID not found",
      "missing_organization",
      undefined,
      {
        message: "No se pudo obtener el ID de la organización",
        code: "ORG_ID_NOT_FOUND",
        context: { userError },
      }
    );
    await debugLogger.finalize("failed", {
      error: {
        message: "No se pudo obtener el ID de la organización",
        code: "ORG_ID_NOT_FOUND",
      },
    });
    throw new Error("No se pudo obtener el ID de la organización");
  }

  const organizationId = userData.organizationId;
  await debugLogger.logAuth(
    "User authenticated successfully",
    "authenticated",
    {
      userId: user.id,
      organizationId,
      role: userData.role,
      email: user.email,
    }
  );

  debugLogger.updateContext({ userId: user.id, organizationId });

  return { user, organizationId, userData };
}

// API Key function
async function getApiKey(
  organizationId: string,
  provider: string,
  debugLogger: DebugLogger
): Promise<ApiKeyResult> {
  await debugLogger.logApiKey("Fetching API key", "fetching", {
    provider: provider.toLowerCase() as any,
    status: "fetching",
    hasValue: false,
  });

  const supabase = await getSupabaseRouteHandler();
  const { data: apiKeyData, error: apiKeyError } = await supabase
    .from("api_key_table")
    .select("key, provider")
    .eq("organizationId", organizationId)
    .eq("provider", provider.toUpperCase() as any)
    .eq("status", "ACTIVE")
    .single();

  console.log(provider, organizationId)

  if (apiKeyError || !apiKeyData) {
    await debugLogger.logApiKey(
      "API key not found",
      "not_found",
      {
        provider: provider.toLowerCase() as any,
        status: "not_found",
        hasValue: false,
      },
      {
        message: "No se pudo obtener la API key para este proveedor",
        code: "API_KEY_NOT_FOUND",
        context: { apiKeyError },
      }
    );
    await debugLogger.finalize("failed", {
      error: {
        message: "No se pudo obtener la API key para este proveedor",
        code: "API_KEY_NOT_FOUND",
      },
    });
    throw new Error("No se pudo obtener la API key para este proveedor");
  }

  if (!apiKeyData.key || apiKeyData.key.trim() === "") {
    await debugLogger.logApiKey("API key is empty or invalid", "empty", {
      provider: provider.toLowerCase() as any,
      status: "empty",
      hasValue: false,
    });
    await debugLogger.finalize("failed", {
      error: {
        message: "La API key está vacía o no es válida",
        code: "API_KEY_EMPTY",
      },
    });
    throw new Error("La API key está vacía o no es válida");
  }

  return apiKeyData;
}

// Tool Configuration function
async function getToolConfig(
  organizationId: string,
  debugLogger: DebugLogger
): Promise<ToolConfig> {
  await debugLogger.logToolConfig("Fetching tool configuration", "fetching", {
    identity: "detector",
    isCustom: false,
    promptsCount: 0,
  });

  const supabase = await getSupabaseRouteHandler();
  const { data: toolData, error: toolError } = await supabase
    .from("tools")
    .select("*")
    .eq("organization_id", organizationId)
    .eq("identity", "detector")
    .single();

  let tool;
  if (toolError) {
    await debugLogger.logToolConfig(
      "Using default tool configuration",
      "using_default",
      { identity: "detector", isCustom: false, promptsCount: 0 }
    );
    const { data: defaultToolData, error: defaultToolError } = await supabase
      .from("default_tools")
      .select("*")
      .eq("identity", "detector")
      .single();

    if (defaultToolError || !defaultToolData) {
      await debugLogger.logToolConfig(
        "Tool configuration not found",
        "not_found",
        undefined,
        {
          message: "No se pudo obtener la configuración de la herramienta",
          code: "TOOL_CONFIG_NOT_FOUND",
          context: { defaultToolError },
        }
      );
      await debugLogger.finalize("failed", {
        error: {
          message: "No se pudo obtener la configuración de la herramienta",
          code: "TOOL_CONFIG_NOT_FOUND",
        },
      });
      throw new Error("No se pudo obtener la configuración de la herramienta");
    }

    tool = defaultToolData;
  } else {
    await debugLogger.logToolConfig(
      "Custom tool configuration found",
      "found_custom",
      {
        identity: "detector",
        isCustom: true,
        promptsCount: toolData.prompts?.length || 0,
        temperature: toolData.temperature,
        topP: toolData.top_p,
        hasSchema: !!toolData.schema,
        promptTitles: toolData.prompts?.map((p: any) => p.title) || [],
      }
    );
    tool = toolData;
  }

  return tool;
}

/**
 * Describe los adjuntos de una sección para el prompt, distinguiendo imágenes
 * de PDFs para que el modelo sepa qué tipo de material recibe.
 */
function describeAttachments(files: any[], category: string): string {
  const images = files.filter((file) => file?.type === "image").length;
  const documents = files.length - images;

  if (files.length === 0) return "No proporcionados";

  const parts: string[] = [];
  if (images > 0) parts.push(`${images} ${images === 1 ? "imagen" : "imágenes"}`);
  if (documents > 0)
    parts.push(`${documents} ${documents === 1 ? "documento PDF" : "documentos PDF"}`);

  return `${parts.join(" y ")} (etiquetados como "${category}")`;
}

// Generate prompt function
function generatePrompt(validatedData: FormSchema): string {
  const links_desinformacion = searchAndReplaceURLText(
    validatedData.disinformation.text,
    validatedData.disinformation.metadata
  );

  const links_verificacion = searchAndReplaceURLText(
    validatedData.verification.text,
    validatedData.verification.metadata
  );

  const contexto = searchAndReplaceURLText(
    validatedData.additional_context.text,
    validatedData.additional_context.metadata
  );

  const transcripciones = formatTranscripts(
    validatedData.additional_context.transcripts
  );

  return `
INSUMOS PARA EL TITULAR Y EL PÁRRAFO INICIAL:

Archivos de la desinformación que circula: ${describeAttachments(
    validatedData.disinformation.images,
    "desinformacion"
  )}

Enlaces de la desinformación que circula:
${links_desinformacion || "No proporcionados"}

¿De qué trata?
${validatedData.disinformation.description}

Calificación: ${getRatingPromptValue(validatedData.rating)}

INSUMOS PARA VERIFICACIÓN Y EVIDENCIAS:

Métodos de verificación con sus enlaces:
${links_verificacion || "No proporcionados"}

Archivos de verificación: ${describeAttachments(
    validatedData.verification.images,
    "verificacion"
  )}

CONTEXTO ADICIONAL:
${contexto || "No proporcionado"}${transcripciones}`;
}



/**
 * Convierte un archivo subido en una parte del mensaje.
 * El cliente manda `preview` como data URL (`data:<mime>;base64,...`), de donde
 * se sacan el media type y el payload. Las imágenes van como parte de imagen y
 * los PDFs como parte de archivo, que los tres proveedores saben leer.
 */
function toContentPart(file: any) {
  const preview: string | undefined = file?.preview;
  if (!preview) return null;

  const match = preview.match(/^data:([^;]+);base64,(.+)$/);
  if (!match) return null;

  const [, mediaType, data] = match;

  if (mediaType.startsWith("image/")) {
    return { type: "image" as const, image: data, mediaType };
  }

  if (mediaType === "application/pdf") {
    return {
      type: "file" as const,
      data,
      mediaType,
      filename: file?.name || "documento.pdf",
    };
  }

  return null;
}

/**
 * Arma el contenido del mensaje: el prompt seguido de los adjuntos,
 * separados por categoría para que el modelo sepa qué está mirando.
 */
function buildUserContent(userPrompt: string, validatedData: FormSchema) {
  const content: any[] = [{ type: "text", text: userPrompt }];

  const sections = [
    {
      label: "--- ARCHIVOS DE LA DESINFORMACIÓN ---",
      files: validatedData.disinformation?.images ?? [],
    },
    {
      label: "--- ARCHIVOS DE VERIFICACIÓN Y EVIDENCIAS ---",
      files: validatedData.verification?.images ?? [],
    },
  ];

  for (const section of sections) {
    const parts = section.files
      .map(toContentPart)
      .filter((part): part is NonNullable<typeof part> => part !== null);

    if (parts.length > 0) {
      content.push({ type: "text", text: section.label });
      content.push(...parts);
    }
  }

  return content;
}

// Función para generar análisis con un modelo específico
async function generateAnalysis(
  modelConfig: { provider: string; model: string },
  systemPrompt: string,
  userPrompt: string,
  toolConfig: ToolConfig,
  apiKey: string,
  debugLogger: DebugLogger,
  validatedData: FormSchema
) {
  debugLogger.info("Iniciando generación de análisis", {
    provider: modelConfig.provider,
    model: modelConfig.model,
  });

  const temperature = toolConfig.temperature;
  const top_p = toolConfig.top_p;

  // Los hiperparámetros se configuran por herramienta, no por generación
  const reasoningEffort =
    toolConfig.reasoning_effort || DEFAULT_REASONING_EFFORT;
  const verbosity = toolConfig.verbosity || DEFAULT_VERBOSITY;

  const content = buildUserContent(userPrompt, validatedData);
  const messages: ModelMessage[] = [{ role: "user", content }];

  debugLogger.info("Contenido del mensaje preparado", {
    imageParts: content.filter((part) => part.type === "image").length,
    fileParts: content.filter((part) => part.type === "file").length,
  });

  switch (modelConfig.provider.toLowerCase()) {
    case "openai":
      debugLogger.info("Usando proveedor OpenAI");
      const openai = createOpenAI({ apiKey });
      return generateText({
        model: openai(modelConfig.model),
        system: systemPrompt,
        messages,
        providerOptions: {
          openai: {
            reasoningEffort,
            textVerbosity: verbosity,
            store: false,
          },
        },
      });

    case "anthropic":
      debugLogger.info("Usando proveedor Anthropic");
      const anthropic = createAnthropic({ apiKey });
      return generateText({
        model: anthropic(modelConfig.model),
        system: systemPrompt,
        messages,
        providerOptions: {
          // `effort` activa el thinking adaptativo; estos modelos no admiten temperature
          anthropic: { effort: anthropicEffort(reasoningEffort) },
        },
      });

    case "google":
      debugLogger.info("Usando proveedor Google");
      const google = createGoogleGenerativeAI({ apiKey });
      return generateText({
        model: google(modelConfig.model),
        system: systemPrompt,
        messages,
        temperature,
        topP: top_p,
      });

    default:
      const errorMsg = `Proveedor no soportado: ${modelConfig.provider}`;
      debugLogger.error(errorMsg);
      throw new Error(errorMsg);
  }
}

/**
 * POST /api/detector
 * Recibe y valida datos del formulario del detector de mentiras
 * Retorna un stream de texto usando AI SDK
 */
export async function POST(request: NextRequest) {
  try {
    const debugLogger = new DebugLogger({
      toolIdentity: "detector",
      source: "detector",
    });

    // Parsear el body de la request
    const body = await request.json();

    // Validar los datos contra el schema
    const validatedData = formSchema.parse(body);

    debugLogger.info("Validacion del formulario completada:", validatedData);

    // 1. Autenticar usuario
    const { organizationId } = await authenticateUser(debugLogger);

    // 2. Obtener configuración de herramienta
    const toolConfig = await getToolConfig(organizationId, debugLogger);

    debugLogger.info("Configuración de herramienta obtenida", {
      temperature: toolConfig.temperature,
      top_p: toolConfig.top_p,
      promptsCount: Array.isArray(toolConfig.prompts) ? toolConfig.prompts.length : 0,
    });

    // 3. Generar prompt
    const prompt = generatePrompt(validatedData);
    const filterPrincipalPrompt = toolConfig.prompts?.find((prompt) => prompt?.title?.toLowerCase() === "principal") || "";
    const systemPrompt = filterPrincipalPrompt.content || "";
    
    debugLogger.info("Prompt combinado generado", {
      systemPromptLength: systemPrompt.length,
      userPromptLength: prompt.length
    });

    // 4. Lógica de comparación vs análisis simple
    if (validatedData.compare && validatedData.model_to_compare_1 && validatedData.selectedModel) {
      debugLogger.info("Modo comparación activado", {
        model1: validatedData.selectedModel,
        model2: validatedData.model_to_compare_1,
      });

      // Obtener API keys para ambos modelos. El orden importa: `generated1`
      // corresponde siempre al modelo principal y `generated2` al de comparación.
      const apiKey1 = await getApiKey(organizationId, validatedData.selectedModel.provider, debugLogger);
      const apiKey2 = await getApiKey(organizationId, validatedData.model_to_compare_1.provider, debugLogger);

      // Generar análisis con ambos modelos de forma simultánea
      const [result1, result2] = await Promise.all([
        generateAnalysis(validatedData.selectedModel, systemPrompt, prompt, toolConfig, apiKey1.key, debugLogger, validatedData),
        generateAnalysis(validatedData.model_to_compare_1, systemPrompt, prompt, toolConfig, apiKey2.key, debugLogger, validatedData),
      ]);

      // Retornar respuesta JSON con ambos resultados
      return NextResponse.json({
        success: true,
        generated1: result1.text,
        generated2: result2.text,
        model1: validatedData.selectedModel,
        model2: validatedData.model_to_compare_1,
      });
    } else {
      debugLogger.info("Modo análisis simple", {
        model: validatedData.selectedModel,
      });

      // Análisis simple con un solo modelo
      const apiKey = await getApiKey(organizationId, validatedData.selectedModel?.provider || "", debugLogger);
      const result = await generateAnalysis(
        validatedData.selectedModel || { provider: "", model: "" },
        systemPrompt,
        prompt,
        toolConfig,
        apiKey.key,
        debugLogger,
        validatedData
      );

      // Retornar respuesta JSON
      return NextResponse.json({
        success: true,
        generated: result.text
      });
    }
  } catch (error) {
    console.error("Error en POST /api/detector:", error);
    return NextResponse.json(
      {
        success: false,
        error: error instanceof Error ? error.message : "Error desconocido",
        generated: ""
      },
      { status: 500 }
    );
  }
}